seed = 0
function = "bin.tabpfnv2_finetune.main"
n_trials = 10
sampler_type = "BruteForceSampler"

[space]
seed = 0
patience = 16
amp = true
n_epochs = -1
batch_size = 1
epoch_size = 10
seq_len_pred = 1024
finetune_mode = "full"

[space.model]
untie_pos_embeddings = false
untie_value_embeddings = false

[space.model.tabpfn_config]
nhead = 6
emsize = 192
nlayers = 12
nhid_factor = 4

[space.model.num_embeddings]
type = "LinearEmbeddings"

[space.data]
seed = 0
num_policy = "noisy-quantile"
cache = true
path = ":data/classif-num-medium-1-MagicTelescope"
old = true

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "categorical",
    [
        4.999998054699972e-06,
        8.340500244230498e-06,
        1.3912793292547576e-05,
        2.320794010302052e-05,
        3.871318040182814e-05,
        6.457747804233804e-05,
        0.00010772173118311912,
        0.00017969068721868098,
        0.00029974215431138873,
        0.0005000000819563866,
    ],
]
weight_decay = 0.0
